fix(RadioCardGroup): use `flex-end` instead of `end` for checked card (#677)
Error: `autoprefixer end value has mixed support consider using flex-end instead`